# Generated by Django 4.1.5 on 2025-01-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_message_options_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
